trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    sudo apt-get -qy install libicu-dev
    python -m pip install --upgrade pip
    CFLAGS="-std=c++11" pip install pyicu
    pip install -e './python[test]'
    pip install -r ./docs/requirements.txt
    pip install pytest-azurepipelines
    npm --prefix ./js install
  displayName: 'Install dependencies'

- script: |
    make check
  displayName: 'Run tests'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: '**/junit.xml'
