trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    set -e
    sudo apt-get -qy install libicu-dev
    pip install pipenv
    echo bistring >python/.venv
    echo bistring >docs/.venv
    (cd python && CFLAGS="-std=c++11" pipenv run pip install pyicu"$(jq -r .develop.pyicu.version Pipfile.lock)")
    (cd python && pipenv run pip install pytest-azurepipelines)
    make deps
  displayName: 'Install dependencies'

- script: |
    make check
  displayName: 'Run tests'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: '**/junit.xml'
