trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'
strategy:
  matrix:
    Python37:
      python.version: '3.7'
    Python38:
      python.version: '3.8'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    set -e
    sudo apt-get -qy install libicu-dev
    pip install pipenv
    echo bistring >python/.venv
    echo bistring >docs/.venv
    make deps
    (cd python && pipenv run pip install pytest-azurepipelines)
  displayName: 'Install dependencies'

- script: |
    make check
  displayName: 'Run tests'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: JUnit
    testResultsFiles: '**/junit.xml'
